services:
  - type: web
    name: sudoku-backend
    runtime: docker
    env: docker
    build:
      dockerfile: Desktop/sudoku-backend/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    port: 8080
